### ISSUE TITLE
Непонятный интерфейс входа

### ISSUE THREAD

**Issue by AlisaBabuh** [amishanov/Kurs#1]
Нет стандартного входа: отсутсвует пароль. Интерфейс показался изначально непонятным.

**Comment by amishanov** [comment]
Мы работает над улучшением пользовательского интерфейса, чтобы пользоваться нашей программой стало ещё приятнее! 
Стоит отметить, что программа "Kurs" предназначена для использования в рамках учебных заведений, вход в програму осуществляется только по паролю-коду, заранее занесённому в базу данных администратором.
Для тестирования программы используются стандартные пароли-коды ("1234" для учителя и "123" для ученика), как и указано в README файле.
